<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OutlookAligner.Outlook.Contracts/OutlookAligner.Outlook.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Outlook" />
  </ItemGroup>
  <Target Name="EmbedOutlookInteropTypes"
          AfterTargets="ResolveReferences"
          BeforeTargets="FindReferenceAssembliesForReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Office.Interop.Outlook' AND '%(ReferencePath.NuGetPackageId)' == 'Microsoft.Office.Interop.Outlook'">
        <EmbedInteropTypes>true</EmbedInteropTypes>
      </ReferencePath>
    </ItemGroup>
  </Target>
</Project>
